### ISSUE TITLE
Upgrade to VS2015

### ISSUE THREAD

**Issue by LeeCampbell** [AdaptiveConsulting/ReactiveTrader#128]
Currently we support VS2012 and VS2013. Can we now support VS2015 ( and potentially drop support for the legacy Visual Studio formats?)

**Comment by raybooysen** [comment]
+1

**Comment by eeldivad** [comment]
+1

**Comment by rikoe** [comment]
Just looking at this - when you say "we support", do you mean the format of the solution files, or something more significant than that?

Re-saving the solution files in 2015 means that this:

    # Visual Studio 2013
    VisualStudioVersion = 12.0.30723.0

changes to this:

    # Visual Studio 14
    VisualStudioVersion = 14.0.23107.0

Based on my tests just about the only thing that this affects is the Visual Studio Version Selector, which picks the version of Visual Studio to open a solution with if you have multiple versions installed.

However, the following line determines the minimum version supported by the solution file:

    MinimumVisualStudioVersion = 10.0.40219.1

Based on this the ReactiveTrader solution can be opened in Visual Studio 2010 or later (incidentally, this is the default, even for a completely new solution file create today in Visual Studio 2015).

So when you say "drop support for VS2012 and V2013", what exactly do you propose that we drop or stop supporting?

Where the solution header does become an issue, I think, is when one person works in Visual Studio 2013 and another works in Visual Studio 2015 - when saving the solution in each version, it will change the solution header to match its convention, so they will constantly be in conflict.

For this reason, it is probably best to update our solutions to 2015, as Visual Studio 2015 Community Edition is free, and there's not a lot of reasons I can think of for someone not to be using that now.

I will create a PR for the solution headers, but it is likely you had more in mind than just that, so please let me know if there's something else to change.

Which leads me to an interesting question: Should we consider upgrading ReactiveTrader to .NET Framework 4.6 and C# 6.0?

**Comment by LeeCampbell** [comment]
Thanks. Great summary.

Re upgrade to. Net 4.6 c#6 yes!
